### ISSUE TITLE
Could you please add this package to MELPA?

### ISSUE THREAD

**Issue by fabio-porcedda** [wentasah/meson-mode#1]
The easiest way to install an emacs packages is using the emacs packages.
Could you please add this meson-mode to https://melpa.org/?

Best regards
Fabio

**Comment by wentasah** [comment]
Pull request submitted: https://github.com/melpa/melpa/pull/4663

**Comment by wentasah** [comment]
Meson mode is now available in Melpa: https://melpa.org/#/meson-mode
