### ISSUE TITLE
regression with indentation of continued lines

### ISSUE THREAD

**Issue by keszybz** [wentasah/meson-mode#11]
The following example
```
system_uid_max = run_command(
  awk,
  'BEGIN { uid=999 } /^\s*SYS_UID_MAX\s+/ { uid=$2 } END { print uid }',
  '/etc/login.defs').stdout()
```
is now indented with 17 spaces instead of two. I hope that's not on purpose ;(
(The whole reason to put the first argument on a separate line instead of directly after "(" is to reduce indentation and also to make the indentation of the arguments independent of the variable name, so that changing the variable name or removing the assignment entirely does not result in a shift of all arguments. This changes breaks both.)

**Comment by wentasah** [comment]
No, that's not on purpose :) Getting the indentation right is tricky (at least for me), because it requires messing up with SMIE default rules and imprecise (but fast) parser. I added your example to the new indentation test file, so hopefully, there will be no regression on this in future.
