### ISSUE TITLE
Add completion

### ISSUE THREAD

**Issue by mattiasb** [wentasah/meson-mode#2]
It would be great to have a nice defun implementing the `completion-at-point-functions` api for meson-mode. Specifically implementing capf is nice since doing it that way auto-completion for vanilla Emacs works out of the box (`C-M-i`) but the user can install something like `ido-at-point` or `company` for something more clever.

I'm not sure how hard this would be though.

**Comment by wentasah** [comment]
I plan to look at this. But one thing at a time :)

**Comment by mattiasb** [comment]
Awesome! :)
