### ISSUE TITLE
Concatenation with directory separator is not portable.

### ISSUE THREAD

**Issue by Janfel** [wentasah/meson-mode#22]
[This line in meson-mode.el](https://github.com/wentasah/meson-mode/blob/d63b85bcb014bb7e5469160183841775200d5a81/meson-mode.el#L898) contains the form `(concat meson-markdown-docs-dir "/" file)`, which [this page of the Emacs Lisp Reference Manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Directory-Names.html) explicitly advises against.

Please use `(expand-file-name file meson-markdown-docs-dir)` instead, or explicitly use `(file-name-as-directory)` and remove the slash.

**Comment by wentasah** [comment]
Fixed. Thanks!
