### ISSUE TITLE
Indentation of ending brackets

### ISSUE THREAD

**Issue by mattiasb** [wentasah/meson-mode#5]
Looking at the `meson.build` file in Graphene I see that indentation of ending brackets behaves a bit differently than I would expect.

See [this line](https://github.com/ebassi/graphene/blob/master/meson.build#L7) for example. If I auto-indent that line it will move 2 chars to the right, but I think the indentation for that ending bracket actually looks fine.

In short, I want this:
```python
        default_options: [
          'buildtype=debugoptimized',
          'c_std=c99',
          'warning_level=1'
        ],
```

Instead of this:

```python
        default_options: [
          'buildtype=debugoptimized',
          'c_std=c99',
          'warning_level=1'
          ],
```

Does this make sense?

**Comment by wentasah** [comment]
I'd also prefer the first variant, but haven't figured out how to express that in terms of SMIE indentation rules. I'll investigate that more deeply.

**Comment by mattiasb** [comment]
\o/
