### ISSUE TITLE
Variable binding depth errors during indent

### ISSUE THREAD

**Issue by mattiasb** [wentasah/meson-mode#8]
Hi!

While reindenting the whole [meson.build](https://github.com/ebassi/graphene/blob/master/meson.build) mentioned in Issue #7 I also got some errors like this:
```
Error: (error "Variable binding depth exceeds max-specpdl-size")
```

In that particular file I got 21 of them.

One example where this happens is on line 223 right after this block:

```

# Check for InitOnce on Windows
if host_system == 'windows'
  init_once_prog = '''
#define _WIN32_WINNT 0x0600
#include <windows.h>
INIT_ONCE g_InitOnce = INIT_ONCE_STATIC_INIT;
BOOL CALLBACK InitHandleFunc (PINIT_ONCE i, PVOID arg, PVOID *ctx) { return TRUE; }
int main (void) {
  BOOL bInitStatus = InitOnceExecuteOnce (&g_InitOnce, InitHandleFunc, NULL, NULL);
  return 0;
}
'''
  if cc.compiles(init_once_prog, name: 'InitOnceExecuteOnce')
    conf.set('HAVE_INIT_ONCE', 1)
  endif
endif
```

However it seems to be dependent on how many lines of code are present before that line, since I'm able to get rid of the error by removing some (to me) arbitrary amount of code in the beginning of the file.

Hope this helps, and that me pestering you with bug reports isn't annoying. :)

**Comment by wentasah** [comment]
> Hope this helps, and that me pestering you with bug reports isn't annoying. :)

It's not annoying. I'm looking into that.

**Comment by wentasah** [comment]
I know what causes this, but when I try to fix that, indentation breaks elsewhere. I'll continue sometimes later.

**Comment by mattiasb** [comment]
Cool!
